<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ASH" failures="1" tests="1" name="testNG_Programs.AssertTestFail" time="7.783" errors="0" timestamp="2024-07-19T10:36:03 IST" skipped="0">
  <testcase classname="testNG_Programs.AssertTestFail" name="verifyExactURLOpensWhileHittingTheURL" time="7.783">
    <failure message="Url is Incorrect  expected [http://selenium.qabible.in/] but found [https://selenium.qabible.in/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Url is Incorrect  expected [http://selenium.qabible.in/] but found [https://selenium.qabible.in/]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at testNG_Programs.AssertTestFail.verifyExactURLOpensWhileHittingTheURL(AssertTestFail.java:27)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
    </failure>
  </testcase> <!-- verifyExactURLOpensWhileHittingTheURL -->
  <system-out/>
</testsuite> <!-- testNG_Programs.AssertTestFail -->
